---
- name: Configure jenkins server
  hosts: all
  sudo: True
  vars:
    jenkins_plugins_extra: ['cloudbees-folder','ssh-agent', 'htmlpublisher']
  roles:
    - users
    - git
    - angstwad.docker_ubuntu
    - karlmdavis.jenkins2
