---
- name: Configure jenkins server
  hosts: all
  become: True
  vars:
    jenkins_plugins_extra: ['cloudbees-folder','ssh-agent','workflow-scm-step', 'artifactory']
    artifactory_database: postgres
    docker_group_members: ['jenkins', 'vagrant']
  roles:
    - users
    - zzet.postgresql
    - bbaassssiiee.artifactory
    - git
    - karlmdavis.jenkins2
    - configure-jenkins
    - angstwad.docker_ubuntu
    - docker_registry
