---
- name: Configure jenkins server
  hosts: all
  become: True
  vars:
    jenkins_plugins_extra: ['cloudbees-folder','ssh-agent','workflow-scm-step']
  roles:
    - users
    - git
    - karlmdavis.jenkins2
    - configure-jenkins