---

  - name: Restart Service 'jenkins'
    service:
      name: jenkins
      state: restarted
    become: true

  - name: Wait for Jenkins HTTP
    uri:
      url: "http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }}/login"
      status_code: 200
    register: jenkins_login_page
    until: jenkins_login_page.status == 200
    retries: 60
    delay: 1

    ########################################
    # Configure credentials for ssh-agent
    ########################################

  - name: List Credentials
    shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }} list-credentials system::system::jenkins"
    register: credentials_list
    changed_when: false

  - name: Copy credentials config files
    copy: src=../credentials-jenkins-ci.xml dest=/etc/credentials-jenkins-ci.xml owner=jenkins

  - name: Create new credentials for jenkins plugins
    shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }} create-credentials-by-xml system::system::jenkins '(global)' <  /etc/credentials-jenkins-ci.xml"
    when: credentials_list.stdout.find('jenkins-ci') == -1

    ########################################
    # Create an example pipeline job
    ########################################

  - name: List Jobs
    shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }} list-jobs"
    register: job_list
    changed_when: false

  - name: Copy jenkins pipeline job xml
    copy: src=../jenkins-pipeline-cs-lab-job.xml dest=/etc/jenkins-pipeline-cs-lab-job.xml owner=jenkins

  - name: Create jenkins pipeline example job
    shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }} create-job jenkins-pipeline-cs-lab <  /etc/jenkins-pipeline-cs-lab-job.xml"
    when: job_list.stdout.find('jenkins-pipeline-cs-lab') == -1
